#!/bin/bash

CC=mpicc \
CXX=mpicxx \
CXXFLAGS='-fexceptions -DBUILD_GYP -std=c++11 ' \
# LDFLAGS='-mmacosx-version-min=10.9' \
nw-gyp \
rebuild \
--target=0.19.5                              # version number of nw.js (not node)

